name: Build and run Docker container

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Create PostgreSQL data directory
        run: |
          sudo mkdir -p /root/mydata/postgresql-data
          sudo chown -R 999:999 /root/mydata/postgresql-data

      - name: Stop running Docker containers
        run: sudo docker compose down || true

      - name: Build and start Docker containers
        run: sudo docker compose up -d --build
