name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }} # Use a personal access token here

      - name: Build and push the image
        run: |
          docker build -t my-python-app .
          docker tag my-python-app ${{ secrets.DOCKER_USERNAME }}/my-python-app
          docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # Install Docker if not already installed
            sudo apt update && sudo apt install -y ca-certificates curl gnupg lsb-release
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt update && sudo apt install -y docker-ce docker-ce-cli containerd.io

            # Start and enable Docker
            sudo systemctl start docker
            sudo systemctl enable docker

            # Add user to Docker group to avoid using sudo
            sudo usermod -aG docker $USER
            newgrp docker

            # Your deployment commands here
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-python-app
            docker stop my-python-app || true
            docker rm my-python-app || true
            docker run -d -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/my-python-app
